version: '3.8'

services:
  library-db:
    image: postgres:17
    container_name: library-db
    environment:
      POSTGRES_DB: library
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5433:5432"
    volumes:
      - library-data:/var/lib/postgresql/data
      - ./db/create_schema.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  library-data:
